import { useState, useEffect } from 'react'
import { 
  CreditCard, Plus, Building2, Wallet, Banknote, 
  Edit2, Trash2, X, DollarSign, MoreVertical,
  CheckCircle, XCircle
} from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/Card'
import { Button } from '../components/ui/Button'
import { supabase } from '../lib/supabase'
import { formatCurrency } from '../lib/utils'

const ACCOUNT_TYPES = [
  { value: 'Bank Account', label: 'Bank Account', icon: Building2, color: 'blue' },
  { value: 'Digital Wallet', label: 'Digital Wallet', icon: Wallet, color: 'purple' },
  { value: 'Cash', label: 'Cash', icon: Banknote, color: 'green' }
]

export function BankAccounts() {
  const [accounts, setAccounts] = useState([])
  const [loading, setLoading] = useState(true)
  const [showAddModal, setShowAddModal] = useState(false)
  const [editingAccount, setEditingAccount] = useState(null)
  const [businesses, setBusinesses] = useState([])
  const [selectedBusinessId, setSelectedBusinessId] = useState(null)
  const [newAccount, setNewAccount] = useState({
    account_name: '',
    account_type: 'Bank Account',
    institution_name: '',
    account_number: '',
    currency_code: 'USD',
    notes: ''
  })

  useEffect(() => {
    fetchBusinesses()
  }, [])

  useEffect(() => {
    if (selectedBusinessId) {
      fetchAccounts()
    }
  }, [selectedBusinessId])

  const fetchBusinesses = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return

      const { data, error } = await supabase
        .from('user_businesses')
        .select('id, name, business_type_id, created_at')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })

      if (error) throw error
      setBusinesses(data || [])
      if (data && data.length > 0) {
        setSelectedBusinessId(data[0].id)
      }
    } catch (error) {
      console.error('Error fetching businesses:', error)
    }
  }

  const fetchAccounts = async () => {
    if (!selectedBusinessId) return
    setLoading(true)
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return

      const { data, error } = await supabase
        .from('bank_accounts')
        .select('*')
        .eq('user_business_id', selectedBusinessId)
        .order('created_at', { ascending: false })

      if (error) throw error
      setAccounts(data || [])
    } catch (error) {
      console.error('Error fetching accounts:', error)
    } finally {
      setLoading(false)
    }
  }

  const saveAccount = async () => {
    if (!newAccount.account_name || !newAccount.account_type) {
      alert('Please fill in required fields')
      return
    }

    if (!selectedBusinessId) {
      alert('Please select a business first')
      return
    }

    try {
      const { data: { user } } = await supabase.auth.getUser()
      
      const accountData = {
        account_name: newAccount.account_name,
        account_type: newAccount.account_type,
        institution_name: newAccount.account_type !== 'Cash' ? newAccount.institution_name : null,
        account_number: newAccount.account_number || null,
        currency_code: newAccount.currency_code,
        notes: newAccount.notes || null
      }
      // Note: account_code and chart_account_id are auto-generated by database trigger on insert

      if (editingAccount) {
        const { error } = await supabase
          .from('bank_accounts')
          .update(accountData)
          .eq('id', editingAccount.id)
        if (error) throw error
      } else {
        const { error } = await supabase
          .from('bank_accounts')
          .insert([{ ...accountData, user_id: user.id, user_business_id: selectedBusinessId }])
        if (error) throw error
      }

      resetForm()
      fetchAccounts()
    } catch (error) {
      console.error('Error saving account:', error)
      alert('Error: ' + error.message)
    }
  }

  const deleteAccount = async (id) => {
    if (!window.confirm('Are you sure you want to delete this account? This will also deactivate the linked Chart of Accounts entry.')) {
      return
    }
    try {
      const { error } = await supabase
        .from('bank_accounts')
        .delete()
        .eq('id', id)
      if (error) throw error
      fetchAccounts()
    } catch (error) {
      console.error('Error deleting account:', error)
    }
  }

  const toggleAccountStatus = async (account) => {
    try {
      const { error } = await supabase
        .from('bank_accounts')
        .update({ is_active: !account.is_active })
        .eq('id', account.id)
      if (error) throw error
      fetchAccounts()
    } catch (error) {
      console.error('Error updating account status:', error)
    }
  }

  const resetForm = () => {
    setNewAccount({
      account_name: '',
      account_type: 'Bank Account',
      institution_name: '',
      account_number: '',
      currency_code: 'USD',
      notes: ''
    })
    setEditingAccount(null)
    setShowAddModal(false)
  }

  const openEditModal = (account) => {
    setEditingAccount(account)
    setNewAccount({
      account_name: account.account_name,
      account_type: account.account_type,
      institution_name: account.institution_name || '',
      account_number: account.account_number || '',
      currency_code: account.currency_code || 'USD',
      notes: account.notes || ''
    })
    setShowAddModal(true)
  }

  const getAccountIcon = (type) => {
    const accountType = ACCOUNT_TYPES.find(t => t.value === type)
    return accountType ? accountType.icon : CreditCard
  }

  const getAccountColor = (type) => {
    const accountType = ACCOUNT_TYPES.find(t => t.value === type)
    return accountType ? accountType.color : 'slate'
  }

  const totalBalance = accounts.reduce((sum, acc) => sum + (parseFloat(acc.current_balance) || 0), 0)
  const activeAccounts = accounts.filter(acc => acc.is_active)

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    )
  }

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-8">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">
              Bank Accounts
            </h1>
            <p className="text-slate-600">
              Manage your bank accounts, digital wallets, and cash
            </p>
          </div>
          <Button onClick={() => setShowAddModal(true)} className="flex items-center space-x-2">
            <Plus className="h-5 w-5" />
            <span>Add Account</span>
          </Button>
        </div>

        {/* Business Selector - Button Style */}
        {businesses.length > 0 && (
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-2">Select Business</label>
            <div className="flex flex-wrap gap-2">
              {businesses.map((business) => (
                <button
                  key={business.id}
                  onClick={() => setSelectedBusinessId(business.id)}
                  className={`px-4 py-2 rounded-lg font-medium transition-all ${
                    selectedBusinessId === business.id
                      ? 'bg-blue-600 text-white shadow-md'
                      : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                  }`}
                >
                  {business.name}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* No Business Warning */}
      {businesses.length === 0 && (
        <Card className="mb-6">
          <CardContent className="py-8 text-center">
            <Building2 className="h-12 w-12 text-amber-500 mx-auto mb-3" />
            <h3 className="text-lg font-semibold text-slate-900 mb-2">No Business Found</h3>
            <p className="text-slate-600">Please create a business first in My Business section to add bank accounts.</p>
          </CardContent>
        </Card>
      )}

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <Card>
          <CardContent className="pt-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-600">Total Balance</p>
                <p className="text-2xl font-bold text-slate-900">{formatCurrency(totalBalance)}</p>
              </div>
              <DollarSign className="h-10 w-10 text-green-500" />
            </div>
          </CardContent>
        </Card>
        
        {ACCOUNT_TYPES.map(type => {
          const typeAccounts = accounts.filter(acc => acc.account_type === type.value && acc.is_active)
          const typeTotal = typeAccounts.reduce((sum, acc) => sum + (parseFloat(acc.current_balance) || 0), 0)
          const Icon = type.icon
          return (
            <Card key={type.value}>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-slate-600">{type.label}</p>
                    <p className="text-xl font-bold text-slate-900">{formatCurrency(typeTotal)}</p>
                    <p className="text-xs text-slate-500">{typeAccounts.length} account(s)</p>
                  </div>
                  <Icon className={`h-10 w-10 text-${type.color}-500`} />
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>

      {/* Accounts List */}
      {accounts.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <CreditCard className="h-16 w-16 text-slate-300 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-slate-900 mb-2">
              No Accounts Added Yet
            </h3>
            <p className="text-slate-600 mb-4">
              Add your bank accounts, digital wallets, or cash to start tracking your finances
            </p>
            <Button onClick={() => setShowAddModal(true)}>Add Your First Account</Button>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {accounts.map(account => {
            const Icon = getAccountIcon(account.account_type)
            const color = getAccountColor(account.account_type)
            return (
              <Card key={account.id} className={`${!account.is_active ? 'opacity-60' : ''}`}>
                <CardContent className="pt-6">
                  <div className="flex items-start justify-between mb-4">
                    <div className={`p-3 rounded-lg bg-${color}-100`}>
                      <Icon className={`h-6 w-6 text-${color}-600`} />
                    </div>
                    <div className="flex items-center space-x-1">
                      {account.is_active ? (
                        <span className="px-2 py-1 text-xs bg-green-100 text-green-700 rounded">Active</span>
                      ) : (
                        <span className="px-2 py-1 text-xs bg-slate-100 text-slate-600 rounded">Inactive</span>
                      )}
                      <button
                        onClick={() => openEditModal(account)}
                        className="p-1 text-slate-400 hover:text-blue-600"
                        title="Edit"
                      >
                        <Edit2 className="h-4 w-4" />
                      </button>
                      <button
                        onClick={() => deleteAccount(account.id)}
                        className="p-1 text-slate-400 hover:text-red-600"
                        title="Delete"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-2 mb-1">
                    <span className="px-2 py-0.5 bg-slate-100 text-slate-700 font-mono text-sm rounded">{account.account_code}</span>
                    <span className="text-xs text-slate-400">Asset</span>
                  </div>
                  <h3 className="font-semibold text-slate-900 text-lg">{account.account_name}</h3>
                  <p className="text-sm text-slate-500 mb-2">{account.account_type}</p>
                  
                  {account.institution_name && (
                    <p className="text-sm text-slate-600 mb-1">
                      <span className="text-slate-500">Institution:</span> {account.institution_name}
                    </p>
                  )}
                  
                  {account.account_number && (
                    <p className="text-sm text-slate-600 mb-1">
                      <span className="text-slate-500">Account #:</span> ****{account.account_number.slice(-4)}
                    </p>
                  )}
                  
                  <div className="mt-4 pt-4 border-t">
                    <div className="flex justify-between items-center">
                      <span className="text-sm text-slate-500">Current Balance</span>
                      <span className={`text-lg font-bold ${parseFloat(account.current_balance) >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                        {formatCurrency(account.current_balance)}
                      </span>
                    </div>
                  </div>

                  <div className="mt-3">
                    <button
                      onClick={() => toggleAccountStatus(account)}
                      className={`text-xs ${account.is_active ? 'text-orange-600 hover:text-orange-800' : 'text-green-600 hover:text-green-800'}`}
                    >
                      {account.is_active ? 'Deactivate Account' : 'Activate Account'}
                    </button>
                  </div>
                </CardContent>
              </Card>
            )
          })}
        </div>
      )}

      {/* Add/Edit Account Modal */}
      {showAddModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <Card className="w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>{editingAccount ? 'Edit Account' : 'Add New Account'}</CardTitle>
                <button onClick={resetForm} className="text-slate-400 hover:text-slate-600">
                  <X className="h-5 w-5" />
                </button>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {/* Account Type Selection */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-2">Account Type *</label>
                  <div className="grid grid-cols-3 gap-2">
                    {ACCOUNT_TYPES.map(type => {
                      const Icon = type.icon
                      const isSelected = newAccount.account_type === type.value
                      return (
                        <button
                          key={type.value}
                          type="button"
                          onClick={() => setNewAccount({ ...newAccount, account_type: type.value, institution_name: type.value === 'Cash' ? '' : newAccount.institution_name })}
                          className={`p-3 rounded-lg border-2 transition-all ${
                            isSelected 
                              ? `border-${type.color}-500 bg-${type.color}-50` 
                              : 'border-slate-200 hover:border-slate-300'
                          }`}
                        >
                          <Icon className={`h-6 w-6 mx-auto mb-1 ${isSelected ? `text-${type.color}-600` : 'text-slate-400'}`} />
                          <p className={`text-xs font-medium ${isSelected ? `text-${type.color}-700` : 'text-slate-600'}`}>
                            {type.label}
                          </p>
                        </button>
                      )
                    })}
                  </div>
                </div>

                {/* Account Name */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Account Name *</label>
                  <input
                    type="text"
                    value={newAccount.account_name}
                    onChange={(e) => setNewAccount({ ...newAccount, account_name: e.target.value })}
                    placeholder="e.g., Main Checking, Savings, Petty Cash"
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                {/* Institution Name - Only for Bank Account and Digital Wallet */}
                {newAccount.account_type !== 'Cash' && (
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Institution Name {newAccount.account_type === 'Bank Account' ? '*' : ''}
                    </label>
                    <input
                      type="text"
                      value={newAccount.institution_name}
                      onChange={(e) => setNewAccount({ ...newAccount, institution_name: e.target.value })}
                      placeholder={newAccount.account_type === 'Bank Account' ? 'e.g., Chase, Bank of America' : 'e.g., PayPal, Venmo, Cash App'}
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                  </div>
                )}

                {/* Account Number - Optional */}
                {newAccount.account_type !== 'Cash' && (
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Account Number (Optional)</label>
                    <input
                      type="text"
                      value={newAccount.account_number}
                      onChange={(e) => setNewAccount({ ...newAccount, account_number: e.target.value })}
                      placeholder="Last 4 digits for reference"
                      className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                  </div>
                )}

                {/* Currency */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Currency</label>
                  <select
                    value={newAccount.currency_code}
                    onChange={(e) => setNewAccount({ ...newAccount, currency_code: e.target.value })}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="USD">USD - US Dollar</option>
                    <option value="EUR">EUR - Euro</option>
                    <option value="GBP">GBP - British Pound</option>
                    <option value="ZAR">ZAR - South African Rand</option>
                    <option value="NGN">NGN - Nigerian Naira</option>
                    <option value="KES">KES - Kenyan Shilling</option>
                    <option value="GHS">GHS - Ghanaian Cedi</option>
                  </select>
                </div>

                {/* Notes */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">Notes (Optional)</label>
                  <textarea
                    value={newAccount.notes}
                    onChange={(e) => setNewAccount({ ...newAccount, notes: e.target.value })}
                    placeholder="Any additional notes about this account"
                    rows={2}
                    className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
                  />
                </div>

                {/* Info Box */}
                <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm space-y-2">
                  <div className="flex items-start gap-2">
                    <div className="mt-0.5">
                      <svg className="h-4 w-4 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <div className="text-blue-700">
                      <p className="font-semibold mb-1">Account Code Assignment</p>
                      <p className="mb-2">A unique 4-digit account code will be automatically assigned:</p>
                      <ul className="space-y-1 ml-2">
                        <li><span className="font-mono font-semibold">10XX</span> - Bank Account (e.g., 1001, 1002)</li>
                        <li><span className="font-mono font-semibold">11XX</span> - Digital Wallet (e.g., 1101, 1102)</li>
                        <li><span className="font-mono font-semibold">12XX</span> - Cash (e.g., 1201, 1202)</li>
                      </ul>
                      <p className="mt-2 text-xs">
                        <strong>Note:</strong> This account will appear in your <strong>Double-Entry Accounting</strong> system under <strong>Assets</strong> in the Chart of Accounts.
                      </p>
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex space-x-3 pt-4">
                  <Button onClick={saveAccount} className="flex-1">
                    {editingAccount ? 'Update Account' : 'Add Account'}
                  </Button>
                  <Button onClick={resetForm} variant="secondary" className="flex-1">
                    Cancel
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}
